baseURL = "https://grohan.co"
title = "Rohan Gupta"
theme = "lines"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
googleAnalytics = "G-QPHTPNYLXE"

[taxonomies]
  tag = "tags"

[Author]
  name = "Rohan Gupta"

[params]
  description = "Rohan Gupta's personal website"
  author = "Rohan Gupta"
  copyright = "Rohan Gupta"
  logo = "images/rohan.jpg"

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = ""
  facebook = ""
  og_image = "images/rohan.jpg"
  sitename = ""
  twitter = ""

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Writing"
    url        = "/posts"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = -20

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
    weight     = -10

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
